myquiz/announcements/urls.py
from django.conf.urls import url
from django.urls import path, include


from . import views
app_name = "announcements"
urlpatterns = [

	path("create", views.CreateAnnouncementView.as_view(), name="create"),
	path("course", views.AnnouncementListView.as_view(), name='announcement-list'),
	path("", views.AllAnnouncements.as_view(), name='all-announcements'),
	path("detail/<int:pk>", views.AnnouncementDetail.as_view(), name='announcement-detail'),
	path("delete/<int:pk>", views.DeleteAnnouncement.as_view(), name='delete'),
	path("about.html", views.about, name="about"),
	path("indexdocs.html", views.indexdocs, name="indexdocs"),

	 
 # _____________ Courses URLs__________________#
    url(r'^api/announcement$', views.Announcement_list),
    url(r'^api/announcement/(?P<pk>[0-9]+)$', views.Announcement_detail),
    url(r'^api/announcement/published$', views.Announcement_list_active),



]

myquiz/myquiz/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    
    path("about", views.about, name="about"),
    path("indexdocs", views.indexdocs, name="indexdocs"),

    path('', include('users.urls')),
	path('', include('quiz.urls')),
    path('', include('assignment.urls')),
    path('announcements/', include('announcements.urls')),
    path('courses/', include('courses.urls')),
    path('about.html', include('courses.urls')),
    path('indexdocs.html', include('courses.urls')),
    
    
    path('api-auth/', include('rest_framework.urls')),

    path('admin', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myquiz/quiz/urls.py
from django.conf.urls import url
from django.urls import path, include

import quiz.views as quiz_views
from . import views
app_name = "quiz"
urlpatterns = [


	path("", views.home, name="home"),
	#path("questions/", views.qpage, name="questions"),


	path("add-quiz", views.CreateQuizView.as_view(), name="create-quiz"),


	#path("create-question/<int:pk>", views.createQuestions, name="create-question"),
	#path("quizzes", views.quizzes, name="quizzes"),
	#temporary
	path("quizzes/<int:pk>", views.QuizListView.as_view(), name="quizzes"),
	#temporary
	path("results", views.results, name="results"),
	path("answers", views.attemptquiz, name="answers"),
	path("attempt-quiz/<int:id>", views.attemptquiz, name="attempt-quiz"),
	path("results/<int:id>", views.result, name="quiz-result"),

	path('htmx/create-quiz-form', views.create_quiz_form, name='create-quiz-form'),
	path("testadd/<int:pk>", views.test_add_quiz, name="create-question"),

     # _____________ Answer URLs__________________#
    url(r'^api/answer$', views.AnswerModel_list),
    url(r'^api/answer/(?P<pk>[0-9]+)$', views.AnswerModel_detail),
    # url(r'^api/answer/published$', views.AnswerModel_list_active),
	
     # _____________ Question URLs__________________#
    url(r'^api/question$', views.QuesModel_list),
    url(r'^api/question/(?P<pk>[0-9]+)$', views.QuesModel_detail),
    # url(r'^api/answer/published$', views.AnswerModel_list_active),
	
     # _____________ Quiz URLs__________________#
    url(r'^api/quiz$', views.QuizModel_list),
    url(r'^api/quiz/(?P<pk>[0-9]+)$', views.QuizModel_detail),
    # url(r'^api/answer/published$', views.AnswerModel_list_active),
	
     # _____________ Result URLs__________________#
    url(r'^api/result$', views.ResultModel_list),
    url(r'^api/result/(?P<pk>[0-9]+)$', views.ResultModel_detail),
    # url(r'^api/answer/published$', views.AnswerModel_list_active),

]

myquiz/announcements/models.py
from django.db import models
from django.utils import timezone
from users.models import User
from courses.models import Course

from django.urls import reverse

# Create your models here.
class Announcement(models.Model):
    subject = models.CharField(max_length=200, blank=False)
    body = models.TextField(blank=False)
    date = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, related_name="announcement", on_delete=models.CASCADE)
    course = models.ForeignKey(Course, related_name="course_announcement", on_delete=models.CASCADE)
    is_general = models.BooleanField(default = False)

    def __str__(self):
        return self.subject

    def get_absolute_url(self):
        return reverse('quiz:home')

myquiz/announcements/forms.py
from django.forms import ModelForm
from django.shortcuts import get_object_or_404

from .models import *



class CreateAnnouncementForm(ModelForm):
    class Meta:
        model = Announcement
        fields = ('subject', 'body')
     #   labels = {
       #     'due_date': 'Due Date (yyyy-mm-dd HH:MM)'
       # }

myquiz/announcements/views.py
from django.views import generic
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from .forms import *
from django.contrib.auth.mixins import (LoginRequiredMixin)

# ___________________ Serializar ______________#
from urllib import request
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_list_or_404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from announcements .models import Announcement
from announcements .serializers import AnnouncementSerializer
from rest_framework.decorators import api_view
from rest_framework.parsers import JSONParser


def about(request):
    return render(request, 'about.html', {})
def indexdocs(request):
    return render(request, 'indexdocs.html', {})
class CreateAnnouncementView(LoginRequiredMixin, generic.CreateView):
    form_class = CreateAnnouncementForm
    template_name = 'announcements/createannouncement_form.html'

    # success_url = reverse('assignments:submit_detail')
    def form_valid(self, form):
        obj = form.save(commit=False)

        obj.author = self.request.user
        obj.course = self.request.session.get('course')

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CreateAnnouncementView, self).get_context_data(**kwargs)

        context['time'] = timezone.now()
        return context

class AllAnnouncements(generic.ListView):

    # All Announcements that concern the logged in student
    model = Announcement
    template_name = 'index.html'


    def get_context_data(self):

        context = super(AllAnnouncements, self).get_context_data()

        if self.request.user.user_type == 1:
            announcements = Announcement.objects.filter(course__in = Course.objects.filter(students=self.request.user))

        else:
            announcements = Announcement.objects.filter(course__in=Course.objects.filter(teacher=self.request.user))

        context['object_list'] = announcements
        return context

class AnnouncementListView(generic.ListView):
    model = Announcement

    def get_context_data(self):

        context = super(AnnouncementListView, self).get_context_data()

        if  self.request.user.user_type ==2:
            context['object_list'] = self.request.user.announcement.all()
        else:
            #show only announcements of the selected Course
            filtered_announcements = Announcement.objects.filter(course__id=self.request.session.get('course'))
            context['object_list'] = filtered_announcements

        return context


class AnnouncementDetail(LoginRequiredMixin, generic.DetailView):
    model = Announcement

    def get_context_data(self, **kwargs):
        context = super(AnnouncementDetail, self).get_context_data(**kwargs)
        announcement = Announcement.objects.get(pk=self.kwargs['pk'])
        context['announcement'] = announcement
        return context

class DeleteAnnouncement(LoginRequiredMixin, generic.DeleteView):
    model = Announcement
    success_url = reverse_lazy('announcements:announcement-list')
    
    
    
    
    # ________________________ Serializer Announcement ____________________--#
    
@api_view(['GET', 'POST', 'DELETE'])
def Announcement_list(request):
    if request.method == 'GET':
        tutorials = Announcement.objects.all()
        
        title = request.query_params.get('subject', None)
        if title is not None:
            tutorials = tutorials.filter(title__icontains=title)
        
        tutorials_serializer = AnnouncementSerializer(tutorials, many=True)
        return JsonResponse(tutorials_serializer.data, safe=False)
        # 'safe=False' for objects serialization
 
    elif request.method == 'POST':
        tutorial_data = JSONParser().parse(request)
        tutorial_serializer = AnnouncementSerializer(data=tutorial_data)
        if tutorial_serializer.is_valid():
            tutorial_serializer.save()
            return JsonResponse(tutorial_serializer.data, status=status.HTTP_201_CREATED) 
        return JsonResponse(tutorial_serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    elif request.method == 'DELETE':
        count = Announcement.objects.all().delete()
        return JsonResponse({'message': '{} Announcement were deleted successfully!'.format(count[0])}, status=status.HTTP_204_NO_CONTENT)
 
 
@api_view(['GET', 'PUT', 'DELETE'])
def Announcement_detail(request, pk):
    try: 
        tutorial = Announcement.objects.get(pk=pk) 
    except Announcement.DoesNotExist: 
        return JsonResponse({'message': 'The Announcement does not exist'}, status=status.HTTP_404_NOT_FOUND) 
 
    if request.method == 'GET': 
        tutorial_serializer = AnnouncementSerializer(tutorial) 
        return JsonResponse(tutorial_serializer.data) 
 
    elif request.method == 'PUT': 
        tutorial_data = JSONParser().parse(request) 
        tutorial_serializer = AnnouncementSerializer(tutorial, data=tutorial_data) 
        if tutorial_serializer.is_valid(): 
            tutorial_serializer.save() 
            return JsonResponse(tutorial_serializer.data) 
        return JsonResponse(tutorial_serializer.errors, status=status.HTTP_400_BAD_REQUEST) 
 
    elif request.method == 'DELETE': 
        tutorial.delete() 
        return JsonResponse({'message': 'Announcement was deleted successfully!'}, status=status.HTTP_204_NO_CONTENT)
    
        
@api_view(['GET'])
def Announcement_list_active(request):
    tutorials = Announcement.objects.filter(published=True)
        
    if request.method == 'GET': 
        tutorials_serializer = AnnouncementSerializer(tutorials, many=True)
        return JsonResponse(tutorials_serializer.data, safe=False)

myquiz/templates/announcements/all_announcements.html
{% extends "base.html" %}

{% block title %}
<title> Assignments</title>
{% endblock  %}



{% block content %}
<style>
    .main {
        margin-inline: 20px;
    }

    .add-button {
        text-align: end;
    }
</style>

<body>
<div class="main">
    <h2>Announcements</h2>

    {%if object_list%}
    <div>
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Subject</th>
                <th scope="col">Teacher</th>
                <th scope="col">Date</th>
            </tr>
            </thead>
            <tbody>

            {% for announcement in object_list %}
            <tr>
                <th scope="row"></th>
                <td><a href="{% url 'announcements:announcement-detail' announcement.id %}"> {{announcement.subject}}</a></td>
                <td>{{announcement.author.username|capfirst}}</td>
                <td>{{announcement.date}}</td>
                {% if user.user_type == 2%}
                <td><button><a href="delete/{{announcement.id}}">Delete</a></button></td>
                {% endif%}
            </tr>
            {% endfor%}



            </tbody>
        </table>
    </div>
    {%if user.user_type == 1 %}
    <div class="add-button">
        <button><a href="{% url 'announcements:create'%}">Create Announcement</a></button>
    </div>
    {% endif%}
    {%else%}


    {%endif%}
</div>
</body>
{% endblock %}

myquiz/templates/announcements/announcement_confirm_delete.html
{% extends 'base.html' %}

{% block title_name %}
    LMS - Confirmation
{% endblock title_name %}
    

{% block content %}
    {% if user.user_type == 2 %}
        <div class="container">
            <div class="jumbotron">
                <h2>Are you sure you want to delete this announcement?</h2>
                <form method="post">
                    {% csrf_token %}
                    <input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
                    <a href="delete/{{announcement.id}}" class="btn btn-primary btn-large">Cancel</a>
                </form>
            </div>
        </div>
    {% else %}
        <div class="container">
            <div class="jumbotron">
                <h2>You are not allowed to delete an assignment.</h2>
            </div>
        </div>
    {% endif %}
        
{% endblock content %}

myquiz/templates/announcements/announcement_detail.html
<style>
    .itemSummaryHeader {
        font-family: "Open Sans", sans-serif;
        font-weight: bold;
        font-size: 14px;
    }
    .portletBody {
        margin-left: 5%;
    }
</style>
<style>
    a {
      text-decoration: none;
      display: inline-block;
      padding: 8px 16px;
    }
    
    a:hover {
      background-color: #ddd;
      color: black;
    }
    
    .previous {
      background-color: #f1f1f1;
      color: black;
    }
    
    .next {
      background-color: #04AA6D;
      color: white;
    }
    
    .round {
      border-radius: 50%;
    }
    </style>
{% extends 'base.html' %}


{% block title_name %}
LMS - ANNOUNCEMENT
{% endblock title_name %}


{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>

</head>
<body>
<a href=".." class = "previous">&laquo; Go Back</a>
<div class="portletBody">


    <h3>Announcement</h3>


    <div class="itemSummary">
        <div class="row">
            <div class="col-lg-4 col-sm-6 col-xs-12">
                <div class="itemSummaryHeader">Title</div>
            </div>
            <div class="col-lg-4 col-sm-6 col-xs-12">
                <div class="itemSummaryValue">
                    {{announcement.subject}}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4 col-sm-6 col-xs-12">
                <div class="itemSummaryHeader">Author</div>
            </div>
            <div class="col-lg-4 col-sm-6 col-xs-12">
                <div class="itemSummaryValue">
                    {{announcement.author}}
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-4 col-sm-6 col-xs-12">
                <div class="itemSummaryHeader">Date</div>
            </div>
            <div class="col-lg-4 col-sm-6 col-xs-12">
                <div class="itemSummaryValue">
                    {{announcement.start_date}}
                </div>
            </div>
        </div>

    </div>
    <div class="clearfix"></div>
    <h4>
        Message
    </h4>

    <div class="textPanel"><p>{{announcement.body}}</p></div>

    <h4>Additional resources for assignment</h4>


    <hr class="itemSeparator">


</div>


</div>
{% endblock content %}

</body>
</html>

myquiz/templates/announcements/announcement_list.html
{% extends "base.html" %}

{% block title %}
<title> Assignments</title>
{% endblock  %}



{% block content %}
<style>
    .main {
        margin-inline: 20px;
    }

    .add-button {
        text-align: end;
    }
</style>

<body>
<a href="/" class = "button">Go Back</a>
<div class="main">
    <h2>Assignments</h2>

    {%if object_list%}
    <div>
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Subject</th>
                <th scope="col">Teacher</th>
                <th scope="col">Date</th>
            </tr>
            </thead>
            <tbody>

            {% for announcement in object_list %}
            <tr>
                <th scope="row">{{announcement.id}}</th>
                <td><a href="detail/{{announcement.id}}"> {{announcement.subject}}</a></td>
                <td>{{announcement.author.username}}</td>
                <td>{{announcement.start_date}}</td>
                {% if user.user_type == 2%}
                <td><button><a href="delete/{{announcement.id}}">Delete</a></button></td>
                {% endif%}
            </tr>
            {% endfor%}


            </tbody>
        </table>
    </div>
    {%if user.user_type == 2 %}
    <div class="add-button">
        <button><a href="{% url 'announcements:create'%}">Create Announcement</a></button>
    </div>
    {% endif%}
    {%else%}
    <div class="add-button">
        <button><a href="{% url 'announcements:create'%}">Create Announcement</a></button>
    </div>


    {%endif%}
</div>
</body>
{% endblock %}

myquiz/templates/announcements/createannouncement_form.html
{% extends "base.html" %}

{% block title_name %}
{% endblock title_name %}

{% load crispy_forms_tags %}
{% block content %}

{% if user.user_type == 2 %}
    <style>@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;700;900&display=swap');

*, body {
    font-family: 'Poppins', sans-serif;
    font-weight: 400;
    -webkit-font-smoothing: antialiased;
    text-rendering: optimizeLegibility;
    -moz-osx-font-smoothing: grayscale;
}

html, body {
    height: 100%;
    background-color: #152733;
    overflow: hidden;
}


.form-holder {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    text-align: center;
    min-height: 100vh;
}

.form-holder .form-content {
    position: relative;
    text-align: center;
    display: -webkit-box;
    display: -moz-box;
    display: -ms-flexbox;
    display: -webkit-flex;
    display: flex;
    -webkit-justify-content: center;
    justify-content: center;
    -webkit-align-items: center;
    align-items: center;
    padding: 60px;
}

.form-content .form-items {
    border: 3px solid #fff;
    padding: 40px;
    display: inline-block;
    width: 100%;
    min-width: 540px;
    -webkit-border-radius: 10px;
    -moz-border-radius: 10px;
    border-radius: 10px;
    text-align: left;
    -webkit-transition: all 0.4s ease;
    transition: all 0.4s ease;
}

.form-content h3 {
    color: #fff;
    text-align: left;
    font-size: 28px;
    font-weight: 600;
    margin-bottom: 5px;
}

.form-content h3.form-title {
    margin-bottom: 30px;
}

.form-content p {
    color: #fff;
    text-align: left;
    font-size: 17px;
    font-weight: 300;
    line-height: 20px;
    margin-bottom: 30px;
}


.form-content label, .was-validated .form-check-input:invalid ~ .form-check-label, .was-validated .form-check-input:valid ~ .form-check-label {
    color: #fff;
}

.form-content input[type=text], .form-content input[type=password], .form-content input[type=email], .form-content select {
    width: 100%;
    padding: 9px 20px;
    text-align: left;
    border: 0;
    outline: 0;
    border-radius: 6px;
    background-color: #fff;
    font-size: 15px;
    font-weight: 300;
    color: #8D8D8D;
    -webkit-transition: all 0.3s ease;
    transition: all 0.3s ease;
    margin-top: 16px;
}


.btn-primary {
    background-color: #6C757D;
    outline: none;
    border: 0px;
    box-shadow: none;
}

.btn-primary:hover, .btn-primary:focus, .btn-primary:active {
    background-color: #495056;
    outline: none !important;
    border: none !important;
    box-shadow: none;
}

.form-content textarea {
    position: static !important;
    width: 100%;
    padding: 8px 20px;
    border-radius: 6px;
    text-align: left;
    background-color: #fff;
    border: 0;
    font-size: 15px;
    font-weight: 300;
    color: #8D8D8D;
    outline: none;
    resize: none;
    height: 120px;
    -webkit-transition: none;
    transition: none;
    margin-bottom: 14px;
}

.form-content textarea:hover, .form-content textarea:focus {
    border: 0;
    background-color: #ebeff8;
    color: #8D8D8D;
}

.mv-up {
    margin-top: -9px !important;
    margin-bottom: 8px !important;
}

.invalid-feedback {
    color: #ff606e;
}

.valid-feedback {
    color: #2acc80;
}</style>

<div class="form-body">
    <div class="row">
        <div class="form-holder">
            <div class="form-content">
                <div class="form-items">
                    <h3>Announcement</h3>

                    <form action="{% url 'announcements:create' %}" method="POST" class="requires-validation" novalidate>
                        {% csrf_token %}
                       {{ form|crispy }}

                        <div class="form-button mt-3">
                            <button id="submit" type="submit" class="btn btn-primary">NEXT</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% else %}

<div class="container">
    <div class="jumbotron">
        <h2>Only Teachers are allowed to create Announcements</h2>
    </div>
</div>


{% endif %}

{% endblock content %}

myquiz/templates/announcements/search_results2.html
<html lang="en">



<head>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


    <link rel="stylesheet" href="test.css">
    <meta charset="UTF-8">
    <title>Search Results</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

</head>


<body>


<div class="container">
    <h1>Similar Drugs</h1>


    <div class="container">
        <div class="row">

            <div class="col-sm-4">

                <div class="box box-down blue">
                    <h2>Physics 101</h2>
                    <p>Sir Isaac Newton</p>
                    <img src="https://assets.codepen.io/2301174/icon-calculator.svg" alt="">
                </div>
            </div>
             <div class="col-sm-4">

                <div class="box box-down blue">
                    <h2>Physics 101</h2>
                    <p>Sir Isaac Newton</p>
                    <img src="https://assets.codepen.io/2301174/icon-calculator.svg" alt="">
                </div>
            </div>
             <div class="col-sm-4">

                <div class="box box-down blue">
                    <h2>Physics 101</h2>
                    <p>Sir Isaac Newton</p>
                    <img src="https://assets.codepen.io/2301174/icon-calculator.svg" alt="">
                </div>
            </div>


        </div>


    </div>
</div>


</body>
</html>

myquiz/templates/announcements/test.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="icon" type="image/png" sizes="32x32" href="./images/favicon-32x32.png">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">


    <title>Frontend Mentor | Four card feature section</title>
    <link rel="stylesheet" href="test.css">
    <link
            href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,400;0,600;1,200;1,400;1,600&display=swap"
            rel="stylesheet">
</head>

<body>
<div class="header">
    <h1>Reliable, efficient delivery</h1>
    <h1>Powered by Technology</h1>

    <p>Our Artificial Intelligence powered tools use millions of project data points
        to ensure that your project is successful</p>
</div>
<div class=container>
      <div class="row">
    <div class="columns">

            <div class="column is-one-third">
                <div class="box box-down blue">
                    <h2>Physics 101</h2>
                    <p>Sir Isaac Newton</p>
                    <img src="https://assets.codepen.io/2301174/icon-calculator.svg" alt="">
                </div>
            </div>
            <div class="column is-one-third">
                <div class="box box-down blue">
                    <h2>Physics 101</h2>
                    <p>Sir Isaac Newton</p>
                    <img src="https://assets.codepen.io/2301174/icon-calculator.svg" alt="">
                </div>
            </div>
            <div class="column is-one-third">
                <div class="box box-down blue">
                    <h2>Physics 101</h2>
                    <p>Sir Isaac Newton</p>
                    <img src="https://assets.codepen.io/2301174/icon-calculator.svg" alt="">
                </div>
            </div>
        </div>
    </div>
</div>


</body>

</html>