myquiz/assignment/urls.py
from django.conf.urls import url
from django.urls import path, include


from . import views
app_name = "assignment"
urlpatterns = [

	path("create", views.CreateAssignment2.as_view(), name="create"),
	path("submit", views.SubmitAssignmentView.as_view(), name="submit"),
	path("assignment-list/<int:pk>", views.AssignmentListView.as_view(), name='assgn-list'),
	path("detail/<int:pk>", views.AssignmentDetail.as_view(), name='detail'),
	#path("submit-detail/<int:pk>", views.AssignmentDetail.as_view(), name='submit-detail'),
	path("submission-detail/<int:pk>", views.SubmitAssignmentDetail.as_view(), name='submit_detail'),
 
     # _____________ Assignment URLs__________________#
    url(r'^api/assignment$', views.assignment_list),
    url(r'^api/assignment/(?P<pk>[0-9]+)$', views.assignment_detail),
    url(r'^api/assignment/published$', views.assignment_list_active),
    
    # _____________ SubmitAssignment URLs__________________#
    url(r'^api/submitassignment$', views.submitAssignment_list),
    url(r'^api/submitassignment/(?P<pk>[0-9]+)$', views.submitAssignment_detail),
    url(r'^api/submitassignment/published$', views.submitAssignment_list_active),



]

myquiz/myquiz/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    
    path("about", views.about, name="about"),
    path("indexdocs", views.indexdocs, name="indexdocs"),

    path('', include('users.urls')),
	path('', include('quiz.urls')),
    path('', include('assignment.urls')),
    path('announcements/', include('announcements.urls')),
    path('courses/', include('courses.urls')),
    path('about.html', include('courses.urls')),
    path('indexdocs.html', include('courses.urls')),
    
    
    path('api-auth/', include('rest_framework.urls')),

    path('admin', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myquiz/quiz/urls.py
from django.conf.urls import url
from django.urls import path, include

import quiz.views as quiz_views
from . import views
app_name = "quiz"
urlpatterns = [


	path("", views.home, name="home"),
	#path("questions/", views.qpage, name="questions"),


	path("add-quiz", views.CreateQuizView.as_view(), name="create-quiz"),


	#path("create-question/<int:pk>", views.createQuestions, name="create-question"),
	#path("quizzes", views.quizzes, name="quizzes"),
	#temporary
	path("quizzes/<int:pk>", views.QuizListView.as_view(), name="quizzes"),
	#temporary
	path("results", views.results, name="results"),
	path("answers", views.attemptquiz, name="answers"),
	path("attempt-quiz/<int:id>", views.attemptquiz, name="attempt-quiz"),
	path("results/<int:id>", views.result, name="quiz-result"),

	path('htmx/create-quiz-form', views.create_quiz_form, name='create-quiz-form'),
	path("testadd/<int:pk>", views.test_add_quiz, name="create-question"),

     # _____________ Answer URLs__________________#
    url(r'^api/answer$', views.AnswerModel_list),
    url(r'^api/answer/(?P<pk>[0-9]+)$', views.AnswerModel_detail),
    # url(r'^api/answer/published$', views.AnswerModel_list_active),
	
     # _____________ Question URLs__________________#
    url(r'^api/question$', views.QuesModel_list),
    url(r'^api/question/(?P<pk>[0-9]+)$', views.QuesModel_detail),
    # url(r'^api/answer/published$', views.AnswerModel_list_active),
	
     # _____________ Quiz URLs__________________#
    url(r'^api/quiz$', views.QuizModel_list),
    url(r'^api/quiz/(?P<pk>[0-9]+)$', views.QuizModel_detail),
    # url(r'^api/answer/published$', views.AnswerModel_list_active),
	
     # _____________ Result URLs__________________#
    url(r'^api/result$', views.ResultModel_list),
    url(r'^api/result/(?P<pk>[0-9]+)$', views.ResultModel_detail),
    # url(r'^api/answer/published$', views.AnswerModel_list_active),

]

myquiz/assignment/models.py
from django.db import models
from django.utils import timezone
from users.models import User
from courses.models import Course
from .widgets import DatePickerInput, TimePickerInput, DateTimePickerInput

from django.urls import reverse

# Create your models here.
class Assignment(models.Model):
    assignment_name = models.CharField(max_length=200, blank=False)
    assignment_description = models.TextField(blank=False)
    start_date = models.DateTimeField(default=timezone.now)
    due_date = models.DateTimeField(blank=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)


    # add a course id

    def __str__(self):
        return self.assignment_name

    def get_absolute_url(self):
        return reverse('assignment:detail', kwargs={'pk': self.pk})



class SubmitAssignment(models.Model):
    author = models.ForeignKey(User, related_name='assignment', on_delete=models.CASCADE)
   # assignment_name = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    assignment_file = models.FileField(blank=False)
    submitted_date = models.DateTimeField(default=timezone.now)
    assignment_ques = models.ForeignKey(Assignment, related_name="question", on_delete=models.CASCADE, null=True)

    def get_absolute_url(self):
        return reverse('quiz:home')

myquiz/assignment/forms.py
from django.forms import ModelForm
from django.shortcuts import get_object_or_404
from django import forms
from .widgets import DatePickerInput, TimePickerInput, DateTimePickerInput
from .models import *


class DateTimePickerInput(forms.DateTimeInput):
    input_type = 'datetime-local'




class CreateAssignmentForm(ModelForm):
    class Meta:
        model = Assignment
        fields = ('assignment_name', 'assignment_description',
                  'due_date')
        widgets = {

            'due_date': DateTimePickerInput(),
        }
     #   labels = {
       #     'due_date': 'Due Date (yyyy-mm-dd HH:MM)'
       # }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        user_object = User.objects.filter(username=user.username)
        new_user_object = get_object_or_404(user_object)




class SubmitAssignmentForm(ModelForm):
    class Meta:
        model = SubmitAssignment
        fields = ('assignment_file',)

    '''''''''
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        assignment = kwargs.pop('assignment_id')
        super().__init__(*args, **kwargs)
        #self.fields['assignment_ques'].queryset = self.fields['assignment_ques'].queryset.filter(pk=assignment)
       # self.fields['author'].queryset = self.fields['author'].queryset.filter(username=user.username)
       
    '''''''''

myquiz/assignment/views.py
from django.shortcuts import render, redirect
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.views.generic.edit import FormMixin
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils import timezone
import os
from django.conf import settings

# from django.contrib import messages
from django.views import generic
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect, render
from .models import *
from .forms import *
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)

#importing serializer requirements
from urllib import request
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_list_or_404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from assignment .models import Assignment
from assignment .models import SubmitAssignment
from assignment .serializers import AssignmentSerializer
from rest_framework.decorators import api_view
from rest_framework.parsers import JSONParser
from assignment .serializers import SubmitAssignmentSerializer

# Create your views here.



class CreateAssignment2(LoginRequiredMixin, generic.CreateView):
    form_class = CreateAssignmentForm
    template_name = 'assignment/createAssignment.html'

    def form_valid(self, form):
        obj = form.save(commit=False)
        course = Course.objects.get(pk=self.request.session.get('course'))
        obj.course = course
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

class DeleteAnnouncement(LoginRequiredMixin, generic.DeleteView):
    model = Assignment
    success_url = reverse_lazy('announcements:announcement-list')
class SubmitAssignmentView(LoginRequiredMixin, generic.CreateView):
    form_class = SubmitAssignmentForm
    template_name = 'assignment/submitassignment_form.html'
    select_related = ('author', 'assignment_ques')

    # success_url = reverse('assignments:submit_detail')
    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        assignments = Assignment.objects.get(pk=self.request.session.get('assignment'))
        obj.assignment_ques = assignments
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        assignments = Assignment.objects.filter(pk=self.request.session.get('assignment'))
        assignment_object = get_object_or_404(assignments)
        context = super(SubmitAssignmentView, self).get_context_data(**kwargs)
        context['duedate'] = assignment_object.due_date
        context['time'] = timezone.now()
        return context



class SubmitAssignmentDetail(LoginRequiredMixin, generic.DetailView):
    model = SubmitAssignment
    template_name = 'assignment/assignment_submissions.html'

    def get_context_data(self, **kwargs):
        submissions = SubmitAssignment.objects.filter(pk=self.kwargs['pk'])
        submissions_object = get_object_or_404(submissions)
        context = super(SubmitAssignmentDetail, self).get_context_data(**kwargs)
        context['submissions'] = submissions_object
        return context


class AssignmentDetail(LoginRequiredMixin, generic.DetailView,generic.FormView):
    model = Assignment
    form_class = SubmitAssignmentForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        assignments = Assignment.objects.get(pk=self.request.session.get('assignment'))
        obj.assignment_ques = assignments
        obj.submitted_date = timezone.now()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        # course_obj = Course.objects.filter(students=self.request.user.id)
        context = super(AssignmentDetail, self).get_context_data(**kwargs)
        # context['course'] = course_obj
        assignment = Assignment.objects.filter(pk=self.kwargs['pk'])
        assignment_object = get_object_or_404(assignment)
        context['duedate'] = assignment_object.due_date
        context['time'] = timezone.now()
        submitassignment = SubmitAssignment.objects.filter(assignment_ques=self.kwargs['pk'])
        context['submitted'] = submitassignment
        self.request.session['assignment'] = self.kwargs['pk']
        # print(self.request.session['assignment'])
        return context


class AssignmentListView(generic.ListView):
    model = Assignment

    def get_context_data(self, **kwargs):

        context = super(AssignmentListView, self).get_context_data(**kwargs)
        filtered_assignments = Assignment.objects.filter(course=self.kwargs['pk'])
        context['object_list'] = filtered_assignments
        return context

    # the default template is (lowercase)<modelname>_list
class AssignmentSubmitDetail(LoginRequiredMixin, generic.DetailView,generic.FormView):

    model = SubmitAssignment


@api_view(['GET', 'POST', 'DELETE'])
def assignment_list(request):
    if request.method == 'GET':
        tutorials = Assignment.objects.all()
        
        title = request.query_params.get('assignment_name', None)
        if title is not None:
            tutorials = tutorials.filter(title__icontains=title)
        
        tutorials_serializer = AssignmentSerializer(tutorials, many=True)
        return JsonResponse(tutorials_serializer.data, safe=False)
        # 'safe=False' for objects serialization
 
    elif request.method == 'POST':
        tutorial_data = JSONParser().parse(request)
        tutorial_serializer = AssignmentSerializer(data=tutorial_data)
        if tutorial_serializer.is_valid():
            tutorial_serializer.save()
            return JsonResponse(tutorial_serializer.data, status=status.HTTP_201_CREATED) 
        return JsonResponse(tutorial_serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    elif request.method == 'DELETE':
        count = Assignment.objects.all().delete()
        return JsonResponse({'message': '{} Assignments were deleted successfully!'.format(count[0])}, status=status.HTTP_204_NO_CONTENT)
 
 
@api_view(['GET', 'PUT', 'DELETE'])
def assignment_detail(request, pk):
    try: 
        tutorial = Assignment.objects.get(pk=pk) 
    except Assignment.DoesNotExist: 
        return JsonResponse({'message': 'The Assignment does not exist'}, status=status.HTTP_404_NOT_FOUND) 
 
    if request.method == 'GET': 
        tutorial_serializer = AssignmentSerializer(tutorial) 
        return JsonResponse(tutorial_serializer.data) 
 
    elif request.method == 'PUT': 
        tutorial_data = JSONParser().parse(request) 
        tutorial_serializer = AssignmentSerializer(tutorial, data=tutorial_data) 
        if tutorial_serializer.is_valid(): 
            tutorial_serializer.save() 
            return JsonResponse(tutorial_serializer.data) 
        return JsonResponse(tutorial_serializer.errors, status=status.HTTP_400_BAD_REQUEST) 
 
    elif request.method == 'DELETE': 
        tutorial.delete() 
        return JsonResponse({'message': 'Assignment was deleted successfully!'}, status=status.HTTP_204_NO_CONTENT)
    
        
@api_view(['GET'])
def assignment_list_active(request):
    tutorials = Assignment.objects.filter(published=True)
        
    if request.method == 'GET': 
        tutorials_serializer = AssignmentSerializer(tutorials, many=True)
        return JsonResponse(tutorials_serializer.data, safe=False)
    
    #__________________________________________________________#Assingent part ended here
    
#________________ Submit Assignment ____________________#

@api_view(['GET', 'POST', 'DELETE'])
def submitAssignment_list(request):
    if request.method == 'GET':
        tutorials = SubmitAssignment.objects.all()
        
        title = request.query_params.get('author', None)
        if title is not None:
            tutorials = tutorials.filter(title__icontains=title)
        
        tutorials_serializer = SubmitAssignmentSerializer(tutorials, many=True)
        return JsonResponse(tutorials_serializer.data, safe=False)
        # 'safe=False' for objects serialization
 
    elif request.method == 'POST':
        tutorial_data = JSONParser().parse(request)
        tutorial_serializer = SubmitAssignmentSerializer(data=tutorial_data)
        if tutorial_serializer.is_valid():
            tutorial_serializer.save()
            return JsonResponse(tutorial_serializer.data, status=status.HTTP_201_CREATED) 
        return JsonResponse(tutorial_serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    elif request.method == 'DELETE':
        count = Assignment.objects.all().delete()
        return JsonResponse({'message': '{} Submitted Assignment were deleted successfully!'.format(count[0])}, status=status.HTTP_204_NO_CONTENT)
 
 
@api_view(['GET', 'PUT', 'DELETE'])
def submitAssignment_detail(request, pk):
    try: 
        tutorial = SubmitAssignment.objects.get(pk=pk) 
    except SubmitAssignment.DoesNotExist: 
        return JsonResponse({'message': 'The Submitted Assignment does not exist'}, status=status.HTTP_404_NOT_FOUND) 
 
    if request.method == 'GET': 
        tutorial_serializer = AssignmentSerializer(tutorial) 
        return JsonResponse(tutorial_serializer.data) 
 
    elif request.method == 'PUT': 
        tutorial_data = JSONParser().parse(request) 
        tutorial_serializer = SubmitAssignmentSerializer(tutorial, data=tutorial_data) 
        if tutorial_serializer.is_valid(): 
            tutorial_serializer.save() 
            return JsonResponse(tutorial_serializer.data) 
        return JsonResponse(tutorial_serializer.errors, status=status.HTTP_400_BAD_REQUEST) 
 

myquiz/templates/assignment/assignment_detail.html
<style>
    .itemSummaryHeader {
        font-family: "Open Sans", sans-serif;
        font-weight: bold;
        font-size: 15px;
    }
</style>
{% extends 'base.html' %}


{% block title_name %}
    LMS - {{ assignment.assignment_name }}
{% endblock title_name %}


{% block content %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
        <head>
            <meta charset="UTF-8">


            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
                  integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
                  crossorigin="anonymous">
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
                    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
                    crossorigin="anonymous"></script>

        </head>
    </head>
    <body>
    <div class="container">
        <div class="portletBody">


            <h3>Assignment
                <span class="highlight">
						 	- In progress
							</span>
            </h3>

            <div class="itemSummary">
                <div class="row">
                    <div class="col-lg-4 col-sm-6 col-xs-12">
                        <div class="itemSummaryHeader">Title</div>
                    </div>
                    <div class="col-lg-4 col-sm-6 col-xs-12">
                        <div class="itemSummaryValue">
                            {{ assignment.assignment_name }}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-4 col-sm-6 col-xs-12">
                        <div class="itemSummaryHeader">Due</div>
                    </div>
                    <div class="col-lg-4 col-sm-6 col-xs-12">
                        <div class="itemSummaryValue">
                            {{ assignment.due_date }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-4 col-sm-6 col-xs-12">
                        <div class="itemSummaryHeader">Status</div>
                    </div>
                    <div class="col-lg-4 col-sm-6 col-xs-12">
                        <div class="itemSummaryValue">
                            Not Started
                        </div>
                    </div>
                </div>

            </div>
            <hr class="itemSeparator">
            <div class="clearfix"></div>
            <h4>
                Instructions
            </h4>

            <div class="textPanel"><p>{{ assignment.assignment_description }}</p></div>

            <hr class="itemSeparator">

            <h4>Additional resources for assignment</h4>


            <hr class="itemSeparator">


        </div>

    </div>
    {% if user.user_type == 2 %}


    {% else %}


        {% if duedate >= time %}


        {% endif %}
        <div class="container">
        <div class="submissions">


            {% for submissions in submitted %}
                {% if submissions.author.id == user.id %}
                    <a href="{% url 'assignment:submit_detail' pk=submissions.pk %}"
                       class="list-group-item list-group-item-action">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">{{ submissions.topic }}</h5>
                            <small>{{ submissions.author }}</small>
                        </div>
                        <p class="mb-1">
                            {{ submissions.description }}
                        </p>
                        <small>Start Date: {{ submissions.submitted_date }}</small><br>
                    </a>
                {% endif %}
            {% empty %}
                <h6>No Submissions</h6>
            {% endfor %}
            {% include "assignment/submitassignment_form.html" %}
        </div>


    {% endif %}
</div>

{% endblock content %}

</body>
</html>

myquiz/templates/assignment/assignment_list.html
{% extends "base.html" %}

{% block title %}
<title> Assignments</title>
{% endblock  %}
{% block content %}



<div style="padding-top: 10px" >
<h1 class="title">Assignments</h1>
 <hr  class="is-divider">

<table class="table table-hover is-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Assignment Title</th>
      <th scope="col">Start Date</th>
      <th scope="col">Due Date
      {%if user.user_type == 2%}
      <th scope="col">
      <button><a href="{%url 'assignment:create' %}">Add</a></button></th>
      {%endif%}

    </tr>
  </thead>
  <tbody>
  {% for assignment in object_list %}
    <tr>
      <th scope="row">{{assignment.id}}</th>
      {% if user.user_type == 1%}
      <td><a href="/detail/{{assignment.id}}"> {{assignment.assignment_name}}</a></td>
      {% else %}
      <td><a href="/submission-detail/{{assignment.id}}"> {{assignment.assignment_name}}</a></td>
      {% endif %}
      <td>{{assignment.start_date}}</td>
      <td>{{assignment.due_date}}</td>
    </tr>
  {% endfor%}

  </tbody>
</table>
</div>
{% endblock %}

myquiz/templates/assignment/assignment_submissions.html
{% extends "base.html" %}

{% block title %}
<title> Submissions</title>
{% endblock  %}
{% block content %}
    <h2>Assignments</h2>




<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Submitted by</th>
      <th scope="col">File</th>
      <th scope="col">Submitted On</th>
    </tr>
  </thead>
  <tbody>

    <tr>
      <th scope="row">{{submissions.id}}</th>
      <td><a href="#"> {{submissions.author.username}}</a></td>
      <td><a  href="{{submissions.assignment_file.url}}">{{submissions.assignment_file}} </a></td>
      <td>{{submissions.submitted_date}}</td>
    </tr>


  </tbody>
</table>

{% endblock %}

myquiz/templates/assignment/createAssignment.html
{% extends "base.html" %}


{% block content %}
{% load crispy_forms_tags %}

<style>@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;700;900&display=swap');

*, body {
    font-family: 'Poppins', sans-serif;
    font-weight: 400;
    -webkit-font-smoothing: antialiased;
    text-rendering: optimizeLegibility;
    -moz-osx-font-smoothing: grayscale;
}

html, body {
    height: 100%;
    background-color: #152733;
    overflow: hidden;
}


.form-holder {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    text-align: center;
    min-height: 100vh;
}

.form-holder .form-content {
    position: relative;
    text-align: center;
    display: -webkit-box;
    display: -moz-box;
    display: -ms-flexbox;
    display: -webkit-flex;
    display: flex;
    -webkit-justify-content: center;
    justify-content: center;
    -webkit-align-items: center;
    align-items: center;
    padding: 60px;
}

.form-content .form-items {
    border: 3px solid #fff;
    padding: 40px;
    display: inline-block;
    width: 100%;
    min-width: 540px;
    -webkit-border-radius: 10px;
    -moz-border-radius: 10px;
    border-radius: 10px;
    text-align: left;
    -webkit-transition: all 0.4s ease;
    transition: all 0.4s ease;
}

.form-content h3 {
    color: #fff;
    text-align: left;
    font-size: 28px;
    font-weight: 600;
    margin-bottom: 5px;
}

.form-content h3.form-title {
    margin-bottom: 30px;
}

.form-content p {
    color: #fff;
    text-align: left;
    font-size: 17px;
    font-weight: 300;
    line-height: 20px;
    margin-bottom: 30px;
}


.form-content label, .was-validated .form-check-input:invalid ~ .form-check-label, .was-validated .form-check-input:valid ~ .form-check-label {
    color: #fff;
}

.form-content input[type=text], .form-content input[type=password], .form-content input[type=email], .form-content select {
    width: 100%;
    padding: 9px 20px;
    text-align: left;
    border: 0;
    outline: 0;
    border-radius: 6px;
    background-color: #fff;
    font-size: 15px;
    font-weight: 300;
    color: #8D8D8D;
    -webkit-transition: all 0.3s ease;
    transition: all 0.3s ease;
    margin-top: 16px;
}


.btn-primary {
    background-color: #6C757D;
    outline: none;
    border: 0px;
    box-shadow: none;
}

.btn-primary:hover, .btn-primary:focus, .btn-primary:active {
    background-color: #495056;
    outline: none !important;
    border: none !important;
    box-shadow: none;
}

.form-content textarea {
    position: static !important;
    width: 100%;
    padding: 8px 20px;
    border-radius: 6px;
    text-align: left;
    background-color: #fff;
    border: 0;
    font-size: 15px;
    font-weight: 300;
    color: #8D8D8D;
    outline: none;
    resize: none;
    height: 120px;
    -webkit-transition: none;
    transition: none;
    margin-bottom: 14px;
}

.form-content textarea:hover, .form-content textarea:focus {
    border: 0;
    background-color: #ebeff8;
    color: #8D8D8D;
}

.mv-up {
    margin-top: -9px !important;
    margin-bottom: 8px !important;
}

.invalid-feedback {
    color: #ff606e;
}

.valid-feedback {
    color: #2acc80;
}</style>

<div class="form-body">
    <div class="row">
        <div class="form-holder">
            <div class="form-content">
                <div class="form-items">
                    <h3>Create a new Assignment</h3>

                    <form action="{% url 'assignment:create' %}" method="POST" class="requires-validation" novalidate>
                        {% csrf_token %}
                       {{ form|crispy }}

                        <div class="form-button mt-3">
                            <button id="submit" type="submit" class="btn btn-primary">NEXT</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

myquiz/templates/assignment/submitassignment_form.html
{% block title_name %}
{% endblock title_name %}
{% load crispy_forms_tags %}
{% block content %}

    {% if user.user_type == 2 %}
        <div class="container">
            <div class="jumbotron">
                <h2>Only students are allowed to submit assignments</h2>
            </div>
        </div>
    {% else %}


        <div >
            <h4>Submit Assignment</h4>
            <form action="{% url 'assignment:submit' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{  form|crispy }}
                {{ form.name.errors }}

                {% if duedate >= time %}
                    <input style="margin-top: 10px" type="submit" value="Submit" class="btn btn-success">
                {% endif %}
            </form>
            <ul>
            </ul>
        </div>
    {% endif %}

{% endblock content %}