myquiz/myquiz/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    
    path("about", views.about, name="about"),
    path("indexdocs", views.indexdocs, name="indexdocs"),

    path('', include('users.urls')),
	path('', include('quiz.urls')),
    path('', include('assignment.urls')),
    path('announcements/', include('announcements.urls')),
    path('courses/', include('courses.urls')),
    path('about.html', include('courses.urls')),
    path('indexdocs.html', include('courses.urls')),
    
    
    path('api-auth/', include('rest_framework.urls')),

    path('admin', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myquiz/quiz/urls.py
from django.conf.urls import url
from django.urls import path, include

import quiz.views as quiz_views
from . import views
app_name = "quiz"
urlpatterns = [


	path("", views.home, name="home"),
	#path("questions/", views.qpage, name="questions"),


	path("add-quiz", views.CreateQuizView.as_view(), name="create-quiz"),


	#path("create-question/<int:pk>", views.createQuestions, name="create-question"),
	#path("quizzes", views.quizzes, name="quizzes"),
	#temporary
	path("quizzes/<int:pk>", views.QuizListView.as_view(), name="quizzes"),
	#temporary
	path("results", views.results, name="results"),
	path("answers", views.attemptquiz, name="answers"),
	path("attempt-quiz/<int:id>", views.attemptquiz, name="attempt-quiz"),
	path("results/<int:id>", views.result, name="quiz-result"),

	path('htmx/create-quiz-form', views.create_quiz_form, name='create-quiz-form'),
	path("testadd/<int:pk>", views.test_add_quiz, name="create-question"),

     # _____________ Answer URLs__________________#
    url(r'^api/answer$', views.AnswerModel_list),
    url(r'^api/answer/(?P<pk>[0-9]+)$', views.AnswerModel_detail),
    # url(r'^api/answer/published$', views.AnswerModel_list_active),
	
     # _____________ Question URLs__________________#
    url(r'^api/question$', views.QuesModel_list),
    url(r'^api/question/(?P<pk>[0-9]+)$', views.QuesModel_detail),
    # url(r'^api/answer/published$', views.AnswerModel_list_active),
	
     # _____________ Quiz URLs__________________#
    url(r'^api/quiz$', views.QuizModel_list),
    url(r'^api/quiz/(?P<pk>[0-9]+)$', views.QuizModel_detail),
    # url(r'^api/answer/published$', views.AnswerModel_list_active),
	
     # _____________ Result URLs__________________#
    url(r'^api/result$', views.ResultModel_list),
    url(r'^api/result/(?P<pk>[0-9]+)$', views.ResultModel_detail),
    # url(r'^api/answer/published$', views.AnswerModel_list_active),

]

myquiz/quiz/models.py
from django.db import models
from courses.models import Course
from django.urls import reverse
from users.models import User


class QuizModel(models.Model):
    Quiz_ID = models.AutoField(primary_key=True)
    course = models.ForeignKey(Course, related_name='quizzes', on_delete=models.CASCADE)
    Quiz_name = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.Quiz_name

    def get_absolute_url(self):
        return reverse('quiz:create-question',kwargs={'pk':self.pk})


class QuesModel(models.Model):
    question = models.CharField(max_length=500)
    option1 = models.CharField(max_length=20)
    option2 = models.CharField(max_length=20)
    option3 = models.CharField(max_length=20)
    option4 = models.CharField(max_length=20)
    answer = models.CharField(max_length=20)
    Quiz_ID = models.ForeignKey(QuizModel, on_delete=models.CASCADE)

    def __str__(self):
        return self.question


class AnswerModel(models.Model):
    Answer_ID = models.AutoField(primary_key=True)
    student = models.ForeignKey(User, related_name="answer", on_delete=models.CASCADE)
    Answer = models.CharField(max_length=200, null=True)
    Question_ID = models.ForeignKey(QuesModel, on_delete=models.CASCADE)
    isCorrect = models.BooleanField(default = True)

class ResultModel(models.Model):
    student = models.ForeignKey(User, related_name="result", on_delete=models.CASCADE)
    Quiz_ID = models.ForeignKey(QuizModel, on_delete=models.CASCADE)
    Marks = models.IntegerField()

myquiz/quiz/forms.py
from django.forms import ModelForm

from .models import *



class addQuizform(ModelForm):
    class Meta:
        model = QuizModel
        fields = ('Quiz_name',)



class addQuestionform(ModelForm):
    class Meta:
        model = QuesModel
        fields = ('question','option1','option2','option3','option4','answer')

class studentAnswerform(ModelForm):
    class Meta:
        model = AnswerModel
        fields = "__all__"

myquiz/quiz/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from .forms import *
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.views import generic
# Serializers import
from urllib import request
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_list_or_404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.parsers import JSONParser
from quiz .models import QuesModel
from quiz .models import QuizModel
from quiz .models import ResultModel
from quiz .models import AnswerModel
from quiz .serializers import QuesModelSerializer
from quiz .serializers import QuizModelSerializer
from quiz .serializers import ResultModelSerializer
from quiz .serializers import AnswerModelSerializer
from courses .models import Course



# Create your views here.
def home(request):
    courses = Course.objects.all()
    context = {'courses': courses}

    return render(request, 'index.html',context)


class CreateQuizView(LoginRequiredMixin, generic.CreateView):

    model  = QuizModel
    form_class = addQuizform
    template_name = 'addquiz.html'
    select_related = ('course')


    # success_url = reverse('assignments:submit_detail')
    def form_valid(self, form):
        obj = form.save(commit=False)
        course = Course.objects.get(pk=self.request.session.get('course'))
        obj.course= course
        self.request.session['quiz'] = obj.Quiz_ID
        return super().form_valid(form)

    def get_context_data(self, **kwargs):

        context = super(CreateQuizView, self).get_context_data(**kwargs)
        return context

@user_passes_test(lambda user: user.user_type == 2)
def test_add_quiz(request,pk):
    form = addQuestionform()
    request.session['quiz'] = pk


    if request.method == 'POST':
        form = addQuestionform(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.Quiz_ID_id = request.session['quiz']
            form.save()
            return HttpResponse('success')
        else:
            return render(request, "quiz/partials/quiz_form.html", context={
                "form": form
            })
    context = {'form': form}
    return render(request, 'quiz/create_questions.html', context)

@user_passes_test(lambda user: user.user_type == 2)
def create_quiz_form(request):
    form = addQuestionform()
    quiz = QuizModel.objects.get(Quiz_ID=request.session['quiz'])
    context = {
        "form": form,
        "quiz":quiz
    }
    return render(request, "quiz/partials/quiz_form.html", context)




@user_passes_test(lambda user: user.user_type == 2)
def createQuestions(request,pk):

    quiz = QuizModel.objects.get(Quiz_ID=pk)
    form = addQuestionform()

    if request.method == 'POST':
        form = addQuestionform(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.Quiz_ID_id =pk
            form.save()
            return HttpResponse("success")
    context = {'form': form}
    return render(request, 'addquestion.html', context)





def quizzes(request,id):
    request.session['course'] = id
    quizzes = QuizModel.objects.filter(course = id)

    return render(request, 'quizzes.html', {'quizzes': quizzes})

class QuizListView(generic.ListView):
    model = QuizModel
    template_name = 'quizzes.html'

    def get_context_data(self, **kwargs):


        context = super(QuizListView, self).get_context_data(**kwargs)

        quizzes = QuizModel.objects.filter(course=self.kwargs['pk'])
        context['object_list'] = quizzes
        self.request.session['course'] = self.kwargs['pk']
        return context


def results(request):
    quizzes = QuizModel.objects.all()

    return render(request, 'Results.html', {'quizzes': quizzes})



def generateresult(id,student_id):

    answers = AnswerModel.objects.filter(Question_ID__Quiz_ID=id ,student = student_id)
    quiz_id = QuizModel.objects.get(Quiz_ID=id)
    correct = 0
    incorrect = 0

    for i in answers:
        if i.isCorrect:
            correct += 1
        else:
            incorrect += 1


    res = ResultModel(Quiz_ID=quiz_id, Marks=correct, student = student_id)
    res.save()

def attemptquiz(request, id):
    questions = QuesModel.objects.filter(Quiz_ID=id)
    student_id = request.user
    if request.method == 'POST':
        dict = request.POST.dict()
        dict.pop('csrfmiddlewaretoken')
        # print(dict.items())

        for k, v in dict.items():
            q_id = QuesModel.objects.get(id=k)
            is_correct = q_id.answer == v
            ans = AnswerModel(Question_ID=q_id, Answer=v, isCorrect=is_correct, student = student_id)
            ans.save()

        answers = AnswerModel.objects.all()



        generateresult(id,student_id)

        return redirect('/')

    return render(request, 'quiz.html', {'questions': questions})


def result(request, id):
    quiz_id = QuizModel.objects.get(Quiz_ID=id)
    results = ResultModel.objects.filter(Quiz_ID=quiz_id, student = request.user )

    if results.exists():

        return render(request, 'result.html', {'results': results})

    else:
        message = 'You havent attempted this quiz yet'
        return render(request, 'result.html', {'message': message})

    return render(request, 'result.html', {'results': results})

# __________________ Serializer View setting ____________________#

# ___________________________________________________________________________________________________________________


#________________For Quiz Model ____________________#

@api_view(['GET', 'POST', 'DELETE'])
def QuizModel_list(request):
    if request.method == 'GET':
        tutorials = QuizModel.objects.all()
        
        title = request.query_params.get('Quiz_name', None)
        if title is not None:
            tutorials = tutorials.filter(title__icontains=title)
        
        tutorials_serializer = QuizModelSerializer(tutorials, many=True)
        return JsonResponse(tutorials_serializer.data, safe=False)
        # 'safe=False' for objects serialization
 
    elif request.method == 'POST':
        tutorial_data = JSONParser().parse(request)
        tutorial_serializer = QuizModelSerializer(data=tutorial_data)
        if tutorial_serializer.is_valid():
            tutorial_serializer.save()
            return JsonResponse(tutorial_serializer.data, status=status.HTTP_201_CREATED) 
        return JsonResponse(tutorial_serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    elif request.method == 'DELETE':
        count = QuizModel.objects.all().delete()
        return JsonResponse({'message': '{} QuizModel were deleted successfully!'.format(count[0])}, status=status.HTTP_204_NO_CONTENT)
 
 
@api_view(['GET', 'PUT', 'DELETE'])
def QuizModel_detail(request, pk):
    try: 
        tutorial = QuizModel.objects.get(pk=pk) 
    except QuizModel.DoesNotExist: 
        return JsonResponse({'message': 'The QuizModel does not exist'}, status=status.HTTP_404_NOT_FOUND) 
 
    if request.method == 'GET': 
        tutorial_serializer = QuizModelSerializer(tutorial) 
        return JsonResponse(tutorial_serializer.data) 
 
    elif request.method == 'PUT': 
        tutorial_data = JSONParser().parse(request) 
        tutorial_serializer = QuizModelSerializer(tutorial, data=tutorial_data) 
        if tutorial_serializer.is_valid(): 
            tutorial_serializer.save() 
            return JsonResponse(tutorial_serializer.data) 
        return JsonResponse(tutorial_serializer.errors, status=status.HTTP_400_BAD_REQUEST) 
 
    elif request.method == 'DELETE': 
        tutorial.delete() 
        return JsonResponse({'message': 'QuizModel was deleted successfully!'}, status=status.HTTP_204_NO_CONTENT)
    
        
@api_view(['GET'])
def QuizModel_list_active(request):
    tutorials = QuizModel.objects.filter(published=True)
        
    if request.method == 'GET': 
        tutorials_serializer = QuizModelSerializer(tutorials, many=True)
        return JsonResponse(tutorials_serializer.data, safe=False)
    
    #__________________________________________________________#QuizModel part ended here
    
    #________________For QuesModel____________________#

@api_view(['GET', 'POST', 'DELETE'])
def QuesModel_list(request):
    if request.method == 'GET':
        tutorials = QuesModel.objects.all()
        
        title = request.query_params.get('Quiz_ID', None)
        if title is not None:
            tutorials = tutorials.filter(title__icontains=title)
        
        tutorials_serializer = QuesModelSerializer(tutorials, many=True)
        return JsonResponse(tutorials_serializer.data, safe=False)
        # 'safe=False' for objects serialization
 
    elif request.method == 'POST':
        tutorial_data = JSONParser().parse(request)
        tutorial_serializer = QuesModelSerializer(data=tutorial_data)
        if tutorial_serializer.is_valid():
            tutorial_serializer.save()
            return JsonResponse(tutorial_serializer.data, status=status.HTTP_201_CREATED) 
        return JsonResponse(tutorial_serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    elif request.method == 'DELETE':
        count = QuesModel.objects.all().delete()
        return JsonResponse({'message': '{} QuesModel were deleted successfully!'.format(count[0])}, status=status.HTTP_204_NO_CONTENT)
 
 
@api_view(['GET', 'PUT', 'DELETE'])
def QuesModel_detail(request, pk):
    try: 
        tutorial = QuesModel.objects.get(pk=pk) 
    except QuesModel.DoesNotExist: 
        return JsonResponse({'message': 'The QuesModel does not exist'}, status=status.HTTP_404_NOT_FOUND) 
 
    if request.method == 'GET': 

myquiz/templates/Results.html
{% extends "base.html" %}




{% block content %}


<div class="container">
  <div class="row row-cols-3">
      {% for q in quizzes %}
    <div class="col"><h1> <a href="{% url  'quiz:quiz-result' q.Quiz_ID  %}" >{{q.Quiz_name}}</a></h1>
    </div>
      {% endfor %}


{% endblock %}
  </div>
</div>

myquiz/templates/about.html
{% extends 'base.html' %}


{% block title_name %}
LMS - ANNOUNCEMENT
{% endblock title_name %}


{% block content %}
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style>
      body {
        font-family: Arial, Helvetica, sans-serif;
        margin: 0;
      }

      html {
        box-sizing: border-box;
      }

      *,
      *:before,
      *:after {
        box-sizing: inherit;
      }

      .column {
        float: left;
        width: 33.3%;
        margin-bottom: 16px;
        padding: 0 8px;
      }

      .card {
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        margin: 8px;
      }

      .about-section {
        padding: 50px;
        text-align: center;
        background-color: #474e5d;
        color: white;
      }

      .container {
        padding: 0 16px;
      }

      .container::after,
      .row::after {
        content: "";
        clear: both;
        display: table;
      }

      .title {
        color: grey;
      }

      .button {
        border: none;
        outline: 0;
        display: inline-block;
        padding: 8px;
        color: white;
        background-color: #000;
        text-align: center;
        cursor: pointer;
        width: 100%;
      }

      .button:hover {
        background-color: #555;
      }

      @media screen and (max-width: 650px) {
        .column {
          width: 100%;
          display: block;
        }
      }
    </style>
  </head>
  <body>
    <div class="about-section">
      <h1>About Us Page</h1>
      <p>Some text about who we are and what we do.</p>
    </div>

    <h2 style="text-align: center">Our Team</h2>
    <div class="row">
      <div class="column">
        <div class="card">
          <img
            src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__340.png"
            alt="Jane"
            style="width: 100%"
          />
          <div class="container">
            <h2>Abdullah Shah</h2>
            <p class="title">Founder</p>
            <p>Some text that describes me lorem ipsum ipsum lorem.</p>
            <p>jane@example.com</p>
            <a class="button" href="tel:312-999-9999">Contact</a>
          </div>
        </div>
      </div>

      <div class="column">
        <div class="card">
          {% comment %} Image Links {% endcomment %}
          <img
            src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__340.png"
            alt="Mike"
            style="width: 100%"
          />
          <div class="container">
            <h2>Saad Sheikh</h2>
            <p class="title">UI Expert</p>
            <p>Some text that describes me lorem ipsum ipsum lorem.</p>
            <p>mike@example.com</p>
            <a class="button" href="tel:312-999-9999">Contact</a>
          </div>
        </div>
      </div>

      <div class="column">
        <div class="card">
          <img
            src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__340.png"
            alt="John"
            style="width: 100%"
          />
          <div class="container">
            <h2>Talha Ahmed</h2>
            <p class="title">Designer</p>
            <p>Some text that describes me lorem ipsum ipsum lorem.</p>
            <p>john@example.com</p>
            {% comment %} <a href="#" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Primary link</a> {% endcomment %}
            {% comment %} <p><button href="tel:8665562570" class="button">Contact</button></p> {% endcomment %}
            <a class="button" href="tel:312-999-9999">Contact</a>
            {% comment %} <li><i class="fas fa-phone mt-4 fa-2x"></i>
                    <p>+ 01 234 567 89</p>
            </li>         {% endcomment %}
          </div>
        </div>
      </div>
    </div>
    
{% endblock content %}
  </body>
</html>

myquiz/templates/addquestion.html
{% extends "base.html" %}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Quiz Creation</title>

</head>
<body>
{% block content %}
    {% load crispy_forms_tags %}

    <a href="/" class="button">Go Back</a>


    <div class="container">
        <div >
            <h2>Add Questions</h2>

            <form action="" method="POST" class="requires-validation" novalidate>
                {% csrf_token %}
                {{ form.non_field_errors }}
                {{ form|crispy }}

                <div class="form-button mt-3">
                    <button id="submit" type="submit" class="btn btn-primary">NEXT</button>
                </div>

            </form>
        </div>
    </div>


{% endblock %}


</body>
</html>

myquiz/templates/answers.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
	<title>Result</title>
	<script src = "{% static 'js/quiz.js' %}"></script>
</head>
<body>
	<div id = "container">
		<header>
			<a href="/" class = "button">Go Back</a>
			<h1>Objective test Question</h1>
		</header>

		<section>
			<div id = "results"></div>
			<form name = "quizForm" method="POST" >
				{% csrf_token %}
			{% for a in answers %}
				<h3> Your answer: {{a.Answer}}</h3>



			{% endfor %}

				<br><br>
				<input type = "submit" value = "Submit Answer">
			</form>
			<br><br>

		</section>
		<footer>
			<p>Copyright &copy;2017, Allright Reserverd</p>
		</footer>
	</div>

</body>
</html>

myquiz/templates/quiz.html
{% extends 'base.html' %}


{% block content %}
    {% load static %}

    <style> *, *:after, *:before {
        box-sizing: border-box;
    }

    body {
        font-family: "Inter", sans-serif;
        color: #000021;
        font-size: calc(1em);
        background-color: #e6e6ef;
    }

    form {
        display: flex;
        flex-wrap: wrap;
        flex-direction: column;
    }

    label {
        display: flex;
        cursor: pointer;
        font-weight: 500;
        position: relative;
        overflow: hidden;
        margin-bottom: 0.375em;
        /* Accessible outline */
        /* Remove comment to use */
        /* &:focus-within {
             outline: .125em solid $primary-color;
        }
         */
    }

    label input {
        position: absolute;
        left: -9999px;
    }

    label input:checked + span {
        background-color: #d6d6e5;
    }

    label input:checked + span:before {
        box-shadow: inset 0 0 0 0.4375em #00005c;
    }

    label span {
        display: flex;
        align-items: center;
        padding: 0.375em 0.75em 0.375em 0.375em;
        border-radius: 99em;
        transition: 0.25s ease;
    }

    label span:hover {
        background-color: #d6d6e5;
    }

    label span:before {
        display: flex;
        flex-shrink: 0;
        content: "";
        background-color: #fff;
        width: 1.5em;
        height: 1.5em;
        border-radius: 50%;
        margin-right: 0.375em;
        transition: 0.25s ease;
        box-shadow: inset 0 0 0 0.125em #00005c;
    }




    </style>

    <div class="container">


        <section>
            <div id="results"></div>
            <form name="quizForm" method="POST">
                {% csrf_token %}
                {% for q in questions %}
                    <h1 style="font-weight: bold; font-size: 1.5em ">  {{ q.question }}</h1>
                    <label>
                    <input type="radio" name="{{ q.id }}" value="{{ q.option1 }}" id="q1a" />
                    <span>{{ q.option1 }}</span>
                    </label>
                    <label>
                    <input type="radio" name="{{ q.id }}" value="{{ q.option2 }}" id="q1b" />
                    <span>{{ q.option2 }}</span>
                    </label>
                    <label>
                    <input type="radio" name="{{ q.id }}" value="{{ q.option3 }}" id="q1c" />
                    <span>{{ q.option3 }}</span>
                    </label>
                    <label>
                    <input type="radio" name="{{ q.id }}" value="{{ q.option4 }}" id="q1d" />
                    <span>{{ q.option4 }}</span>
                    </label>



                {% endfor %}




                <input class="button is-primary" type="submit" value="Submit Answer">
            </form>
            <br><br>
            <a href="{% url  'quiz:answers' %}">RESET</a>
        </section>

        <form>

        </form>

    </div>
{% endblock %}

myquiz/templates/quizzes.html
<!doctype html>
<link rel="stylesheet" href="../static/courses/course_list.css">
{% extends "base.html" %}
{% block content %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="../static/courses/course_list.css">

    <title>Courses</title>

</head>



<div class="container">
    <div>
        <h1 id="heading" style="font-size: 50px">Quizzes</h1>
        {% if user.user_type == 2%}
        <div>
            <button><a href="/add-quiz">Create Quiz</a></button>
        </div>
        {%endif%}
    </div>


    <div class="">
        <div class="">
            <div class="row">


                {% for q in object_list %}
                <div class="col-sm-4">

                    <div class="box box-down blue">
                        <h4>
                            <a  class ="box-name" href="{% url 'quiz:attempt-quiz' q.Quiz_ID %}">{{q.Quiz_name}}</a>
                        </h4>
                        <h3 style="padding-top: 10px"><a href="{% url 'quiz:quiz-result' q.Quiz_ID %}">Result</a></h3>

                    </div>
                </div>
                {% endfor %}


            </div>
        </div>
    </div>

</div>

</html>
{% endblock content %}

myquiz/templates/result.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
	<title>Quiz Application</title>
	<script src = "{% static 'js/quiz.js' %}"></script>
</head>
<body>
	<div id = "container">
		<header>
			<a href="/" class = "button">Go Back</a>
			<h1>Result</h1>
		</header>

		<section>
			<div id = "results"></div>

				{% csrf_token %}
			<h3> {{message}}</h3>
			{% for i in results %}


            <h3> You got   {{ i.Marks }} Marks in {{ i.Quiz_ID }}</h3>



			{% endfor %}


			<br><br>

		</section>
		<footer>
			<p>Copyright &copy;2017, Allright Reserverd</p>
		</footer>
	</div>

</body>
</html>

myquiz/templates/username.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
    <script src = "{% static 'js/quiz.js' %}"></script>
</head>

    <div class="container">
      <div class="login">
        <h1>Login</h1>
        <form method="post" action="/questions/" onsubmit="getName()">
        {% csrf_token %}
          <p><input type="text" id="login" value="" placeholder="Username or Email" required></p>
          <p><input type="password" name="password" value="" placeholder="Password" required></p>
          <p class="remember_me">
            <input type="checkbox" name="remember_me" id="remember_me" checked>
            <label for="remember_me"><span class="box"></span>Remember me on this computer</label>
            </p>
          <p class="submit"><input type="submit" name="commit" value="Login"></p>
        </form>
      </div>
    </div>
</html>