myquiz/announcements/urls.py
from django.conf.urls import url
from django.urls import path, include


from . import views
app_name = "announcements"
urlpatterns = [

	path("create", views.CreateAnnouncementView.as_view(), name="create"),
	path("course", views.AnnouncementListView.as_view(), name='announcement-list'),
	path("", views.AllAnnouncements.as_view(), name='all-announcements'),
	path("detail/<int:pk>", views.AnnouncementDetail.as_view(), name='announcement-detail'),
	path("delete/<int:pk>", views.DeleteAnnouncement.as_view(), name='delete'),
	path("about.html", views.about, name="about"),
	path("indexdocs.html", views.indexdocs, name="indexdocs"),

	 
 # _____________ Courses URLs__________________#
    url(r'^api/announcement$', views.Announcement_list),
    url(r'^api/announcement/(?P<pk>[0-9]+)$', views.Announcement_detail),
    url(r'^api/announcement/published$', views.Announcement_list_active),



]

myquiz/assignment/urls.py
from django.conf.urls import url
from django.urls import path, include


from . import views
app_name = "assignment"
urlpatterns = [

	path("create", views.CreateAssignment2.as_view(), name="create"),
	path("submit", views.SubmitAssignmentView.as_view(), name="submit"),
	path("assignment-list/<int:pk>", views.AssignmentListView.as_view(), name='assgn-list'),
	path("detail/<int:pk>", views.AssignmentDetail.as_view(), name='detail'),
	#path("submit-detail/<int:pk>", views.AssignmentDetail.as_view(), name='submit-detail'),
	path("submission-detail/<int:pk>", views.SubmitAssignmentDetail.as_view(), name='submit_detail'),
 
     # _____________ Assignment URLs__________________#
    url(r'^api/assignment$', views.assignment_list),
    url(r'^api/assignment/(?P<pk>[0-9]+)$', views.assignment_detail),
    url(r'^api/assignment/published$', views.assignment_list_active),
    
    # _____________ SubmitAssignment URLs__________________#
    url(r'^api/submitassignment$', views.submitAssignment_list),
    url(r'^api/submitassignment/(?P<pk>[0-9]+)$', views.submitAssignment_detail),
    url(r'^api/submitassignment/published$', views.submitAssignment_list_active),



]

myquiz/courses/urls.py
from django.conf.urls import url
from django.urls import path, include


from . import views
app_name = "courses"
urlpatterns = [


	path("course-list", views.CourseListView.as_view(), name='course-list'),
	path("detail/<int:pk>", views.CourseDetail.as_view(), name='course-detail'),
    path("select/<int:pk>", views.select_course, name='course-select'),
 
     # _____________ Courses URLs__________________#
    url(r'^api/courses$', views.course_list),
    url(r'^api/courses/(?P<pk>[0-9]+)$', views.course_detail),
    url(r'^api/courses/published$', views.course_list_active),
    
    # _____________ Enrollment URLs__________________#
    url(r'^api/enrollment$', views.enrollment_list),
    url(r'^api/enrollment/(?P<pk>[0-9]+)$', views.enrollment_detail),
    url(r'^api/enrollment/published$', views.Enrollment_list_active),
]

myquiz/myquiz/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    
    path("about", views.about, name="about"),
    path("indexdocs", views.indexdocs, name="indexdocs"),

    path('', include('users.urls')),
	path('', include('quiz.urls')),
    path('', include('assignment.urls')),
    path('announcements/', include('announcements.urls')),
    path('courses/', include('courses.urls')),
    path('about.html', include('courses.urls')),
    path('indexdocs.html', include('courses.urls')),
    
    
    path('api-auth/', include('rest_framework.urls')),

    path('admin', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myquiz/quiz/urls.py
from django.conf.urls import url
from django.urls import path, include

import quiz.views as quiz_views
from . import views
app_name = "quiz"
urlpatterns = [


	path("", views.home, name="home"),
	#path("questions/", views.qpage, name="questions"),


	path("add-quiz", views.CreateQuizView.as_view(), name="create-quiz"),


	#path("create-question/<int:pk>", views.createQuestions, name="create-question"),
	#path("quizzes", views.quizzes, name="quizzes"),
	#temporary
	path("quizzes/<int:pk>", views.QuizListView.as_view(), name="quizzes"),
	#temporary
	path("results", views.results, name="results"),
	path("answers", views.attemptquiz, name="answers"),
	path("attempt-quiz/<int:id>", views.attemptquiz, name="attempt-quiz"),
	path("results/<int:id>", views.result, name="quiz-result"),

	path('htmx/create-quiz-form', views.create_quiz_form, name='create-quiz-form'),
	path("testadd/<int:pk>", views.test_add_quiz, name="create-question"),

     # _____________ Answer URLs__________________#
    url(r'^api/answer$', views.AnswerModel_list),
    url(r'^api/answer/(?P<pk>[0-9]+)$', views.AnswerModel_detail),
    # url(r'^api/answer/published$', views.AnswerModel_list_active),
	
     # _____________ Question URLs__________________#
    url(r'^api/question$', views.QuesModel_list),
    url(r'^api/question/(?P<pk>[0-9]+)$', views.QuesModel_detail),
    # url(r'^api/answer/published$', views.AnswerModel_list_active),
	
     # _____________ Quiz URLs__________________#
    url(r'^api/quiz$', views.QuizModel_list),
    url(r'^api/quiz/(?P<pk>[0-9]+)$', views.QuizModel_detail),
    # url(r'^api/answer/published$', views.AnswerModel_list_active),
	
     # _____________ Result URLs__________________#
    url(r'^api/result$', views.ResultModel_list),
    url(r'^api/result/(?P<pk>[0-9]+)$', views.ResultModel_detail),
    # url(r'^api/answer/published$', views.AnswerModel_list_active),

]

myquiz/courses/models.py
from django.db import models
from django.urls import reverse
from users.models import User

# Create your models here.
class Course(models.Model):
    course_name = models.CharField(max_length=200)
    course_description = models.TextField()
    teacher = models.ForeignKey(User, related_name="course", on_delete=models.CASCADE)
    students = models.ManyToManyField(User, through='Enrollment', related_name="student_course")

    def __str__(self):
        return self.course_name

    def get_absolute_url(self):
        return reverse('courses:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['course_name']

class Enrollment(models.Model):
    course = models.ForeignKey(Course, related_name="enrollments",on_delete=models.CASCADE)
    student = models.ForeignKey(User, related_name="user_courses", on_delete=models.CASCADE)

    def __str__(self):
        str = self.student.username +" | "+ self.course.course_name
        return str

    class Meta:
        unique_together = ('course', 'student')

myquiz/courses/views.py
from django.views import generic

from courses.models import Course, Enrollment
from assignment.models import Assignment
# Create your views here.


#importing serializer requirements
from urllib import request
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_list_or_404 ,redirect
from rest_framework.views import APIView
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.parsers import JSONParser
from courses .serializers import CourseSerializer
from courses .serializers import EnrollmentSerializer
from courses .models import Course
from courses .models import Enrollment

class CourseDetail(generic.DetailView):
    model = Course
    template_name = 'courses/course_detail.html'

    def get_context_data(self,**kwargs):
        assignments = Assignment.objects.filter(course=self.kwargs['pk'])
        context = super(CourseDetail, self).get_context_data(**kwargs)
        context['assignments'] = assignments
        self.request.session['course'] = self.kwargs['pk']
        return context
    #saves the id of the selected course to the request.session so it can be used to select relevant assigments/quizzes/announcements


def select_course(request,pk):
    course = Course.objects.get(id=pk)
    request.session['course_name'] = course.course_name
    request.session['course'] = pk
    return redirect('/')


class CourseListView(generic.ListView):

    model = Course
   # courses = Course.objects.filter()
   
   
#________________For Courses____________________#
@api_view(['GET', 'POST', 'DELETE'])
def course_list(request):
    if request.method == 'GET':
        tutorials = Course.objects.all()
        
        title = request.query_params.get('course_name', None)
        if title is not None:
            tutorials = tutorials.filter(title__icontains=title)
        
        tutorials_serializer = CourseSerializer(tutorials, many=True)
        return JsonResponse(tutorials_serializer.data, safe=False)
        # 'safe=False' for objects serialization
 
    elif request.method == 'POST':
        tutorial_data = JSONParser().parse(request)
        tutorial_serializer = CourseSerializer(data=tutorial_data)
        if tutorial_serializer.is_valid():
            tutorial_serializer.save()
            return JsonResponse(tutorial_serializer.data, status=status.HTTP_201_CREATED) 
        return JsonResponse(tutorial_serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    elif request.method == 'DELETE':
        count = Course.objects.all().delete()
        return JsonResponse({'message': '{} Courses were deleted successfully!'.format(count[0])}, status=status.HTTP_204_NO_CONTENT)
 
 
@api_view(['GET', 'PUT', 'DELETE'])
def course_detail(request, pk):
    try: 
        tutorial = Course.objects.get(pk=pk) 
    except Course.DoesNotExist: 
        return JsonResponse({'message': 'The Course does not exist'}, status=status.HTTP_404_NOT_FOUND) 
 
    if request.method == 'GET': 
        tutorial_serializer = CourseSerializer(tutorial) 
        return JsonResponse(tutorial_serializer.data) 
 
    elif request.method == 'PUT': 
        tutorial_data = JSONParser().parse(request) 
        tutorial_serializer = CourseSerializer(tutorial, data=tutorial_data) 
        if tutorial_serializer.is_valid(): 
            tutorial_serializer.save() 
            return JsonResponse(tutorial_serializer.data) 
        return JsonResponse(tutorial_serializer.errors, status=status.HTTP_400_BAD_REQUEST) 
 
    elif request.method == 'DELETE': 
        tutorial.delete() 
        return JsonResponse({'message': 'Course was deleted successfully!'}, status=status.HTTP_204_NO_CONTENT)
    
        
@api_view(['GET'])
def course_list_active(request):
    tutorials = Course.objects.filter(published=True)
        
    if request.method == 'GET': 
        tutorials_serializer = CourseSerializer(tutorials, many=True)
        return JsonResponse(tutorials_serializer.data, safe=False)
    
    #__________________________________________________________#Course part ended here
    
#________________Enrollment____________________#

@api_view(['GET', 'POST', 'DELETE'])
def enrollment_list(request):
    if request.method == 'GET':
        tutorials = Enrollment.objects.all()
        
        title = request.query_params.get('course', None)
        if title is not None:
            tutorials = tutorials.filter(title__icontains=title)
        
        tutorials_serializer = EnrollmentSerializer(tutorials, many=True)
        return JsonResponse(tutorials_serializer.data, safe=False)
        # 'safe=False' for objects serialization
 
    elif request.method == 'POST':
        tutorial_data = JSONParser().parse(request)
        tutorial_serializer = EnrollmentSerializer(data=tutorial_data)
        if tutorial_serializer.is_valid():
            tutorial_serializer.save()
            return JsonResponse(tutorial_serializer.data, status=status.HTTP_201_CREATED) 
        return JsonResponse(tutorial_serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    elif request.method == 'DELETE':
        count = Enrollment.objects.all().delete()
        return JsonResponse({'message': '{} Enrollment were deleted successfully!'.format(count[0])}, status=status.HTTP_204_NO_CONTENT)
 
 
@api_view(['GET', 'PUT', 'DELETE'])
def enrollment_detail(request, pk):
    try: 
        tutorial = Enrollment.objects.get(pk=pk) 
    except Enrollment.DoesNotExist: 
        return JsonResponse({'message': 'The Enrollment does not exist'}, status=status.HTTP_404_NOT_FOUND) 
 
    if request.method == 'GET': 
        tutorial_serializer = EnrollmentSerializer(tutorial) 
        return JsonResponse(tutorial_serializer.data) 
 
    elif request.method == 'PUT': 
        tutorial_data = JSONParser().parse(request) 
        tutorial_serializer = EnrollmentSerializer(tutorial, data=tutorial_data) 
        if tutorial_serializer.is_valid(): 
            tutorial_serializer.save() 
            return JsonResponse(tutorial_serializer.data) 
        return JsonResponse(tutorial_serializer.errors, status=status.HTTP_400_BAD_REQUEST) 
 
    elif request.method == 'DELETE': 
        tutorial.delete() 
        return JsonResponse({'message': 'Enrollment was deleted successfully!'}, status=status.HTTP_204_NO_CONTENT)
    
        
@api_view(['GET'])
def Enrollment_list_active(request):
    tutorials = Enrollment.objects.filter(published=True)
        
    if request.method == 'GET': 
        tutorials_serializer = EnrollmentSerializer(tutorials, many=True)
        return JsonResponse(tutorials_serializer.data, safe=False)
    
    #__________________________________________________________#Enrollment part ended here
    

myquiz/templates/courses/course_detail.html
<!doctype html>
<link rel="stylesheet" href="../static/courses/course_list.css">
{% extends "base.html" %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="../static/courses/course_list.css">

    <title>Courses</title>

</head>
<body>

{% block content %}

    <div class="container">

        <div style="padding: 10px">
            <h1 id="heading" style="font-size: 50px">{{ course.course_name }}</h1>
        </div>

        <div class="container">
            <div class="container">
                <div class="row">


                    <div class="col-sm-4">

                        <div class="box box-down blue">
                            <h2>
                                <a class="box-name" href="{% url  'quiz:quizzes' course.id %}">Quizzes</a>
                            </h2>

                        </div>
                    </div>
                    <div class="col-sm-4">

                        <div class="box box-down blue">
                            <h2>
                                <a class="box-name" href="{% url  'assignment:assgn-list' course.id %}">Assignments</a>
                            </h2>

                        </div>
                    </div>
                    <div class="col-sm-4">

                        <div class="box box-down blue">
                            <h2>
                                <a class="box-name"
                                   href="{% url  'announcements:announcement-list' %}">Announcements</a>
                            </h2>

                        </div>
                    </div>


                </div>
            </div>
        </div>

    </div>

{% endblock content %}
</div>
</body>
</html>

myquiz/templates/courses/course_list.html
<!doctype html>
<link rel="stylesheet" href="../static/courses/course_list.css">
{% extends "base.html" %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="../static/courses/course_list.css">

    <title>Courses</title>

</head>
<body>
{% block title_name %}
LMS - Courses
{% endblock title_name %}

{% block content %}
<div class="container">
    <div>
        <h2 id="heading" style="font-size: 50px">All Courses</h2>
    </div>


    <div class="container">
        <div class="container">
            <div class="row">

                {% for course_item in object_list %}

                {% if user.user_type == 2%}

                {% if user == course_item.teacher %}

                 <div class="col-sm-4">

                    <div class="box box-down blue">
                        <h2>
                            <a href="{% url 'courses:course-detail' course_item.id %}">{{course_item.course_name}}</a>
                        </h2>
                        <p>{{course_item.teacher}}</p>
                        <p>{{course_item.course_description}}</p>
                    </div>
                </div>

                {% endif%}

                {% endif %}

                {% if user in course_item.students.all%}


                <div class="col-sm-4">

                    <div class="box box-down blue">
                        <h2>
                            <a href="{% url 'courses:course-detail' course_item.id %}">{{course_item.course_name}}</a>
                        </h2>
                        <p>{{course_item.teacher}}</p>
                        <p>{{course_item.course_description}}</p>
                    </div>
                </div>


                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>

</div>

{% endblock content %}
</div>
</body>
</html>